### ISSUE TITLE
high cpu usage after day of gpu only mining

### ISSUE THREAD

**Issue by professor-jonny** [angelbbs/NiceHashMinerLegacy#88]
I seem to have a problem with forkfix 24 eating up cpu usage when not actually mining after running for several hours gpu mining.

looking in task manager no background cpu mining is going on just the application.

Closing the program down resolves the issue.

**Comment by professor-jonny** [comment]
![New Bitmap Image](https://user-images.githubusercontent.com/35296809/75330951-cb044b00-58e6-11ea-93a3-a25a0aadce23.jpg)

**Comment by angelbbs** [comment]
https://github.com/angelbbs/NiceHashMinerLegacy/releases
Fixed broken new version alert
Fixed broken EWBF miner
Fixed high CPU load by WMI service
Added additional feature "Always on Top"

**Comment by professor-jonny** [comment]
Cool ill give it a try.

**Comment by barelymining** [comment]
I updated to 24.1 and keep seeing WMI Provider host heating up the CPU :). Its not as high as with 24.0 but the issue is still there.  As soon as I close Nicehash the process CPU % goes down to 0. What changed?

**Comment by angelbbs** [comment]
will be fixed in next release or try https://github.com/angelbbs/NiceHashMinerLegacy/blob/master-old/LatestBuild/nhmlffLatest.zip
unpack zip-file into existing folder with program

**Comment by barelymining** [comment]
So far so good. It has been running for a couple of hours now with no issues. Thanks!

**Comment by professor-jonny** [comment]
same here seems ok with this update other than the thousands of 1kB files in the download

**Comment by angelbbs** [comment]
oops, sorry. del *.pkt files manually
fixed https://github.com/angelbbs/NiceHashMinerLegacy/blob/master-old/LatestBuild/nhmlffLatest.zip
